version: '3.7'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=avatar-generator
    ports:
      - 3306:3306
    volumes:
      - avatar-gen:/var/lib/mysql

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  avatar-gen:
